apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ML-model
  labels:
    app: model
  name: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - image: evgenii.saurov/model
        name: model