pipeline {
    agent any
    environment {
        PROJECT_ID = 'PROJECT-ID'
        LOCATION = 'CLUSTER-LOCATION'
        CREDENTIALS_ID = 'gke'
        CLUSTER_NAME_TEST = 'CLUSTER-NAME-1'
        CLUSTER_NAME_PROD = 'CLUSTER-NAME-2'
    }
    stages {
        stage("Clone") {
            steps {
                git branch: "master", url: 'https://github.com/polkadot21/jenkins'
            }
        }

        stage("Build image") {
            steps {
                script {
                    sh "docker build -t model:v1 ."
                }
            }
        }
        stage('Deploy to the test cluster') {
            steps{
                sh "kubectl apply -f ."

            }
        }

        stage('Deploy to the production cluster') {
            steps{
                input message:"Proceed with final deployment?"
                step([$class: 'KubernetesEngineBuilder', projectId: env.PROJECT_ID, clusterName: env.CLUSTER_NAME_PROD, location: env.LOCATION, manifestPattern: 'deployment.yaml', credentialsId: env.CREDENTIALS_ID, verifyDeployments: true])
            }
        }
    }
}