apiVersion: v1
kind: Service
metadata:
  namespace: ML-model
  labels:
    app: model
  name: model
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: model
  type: LoadBalancer